export enum DayEnum {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

export enum HolidayTypeEnum {
  IMMOVABLE = "IMMOVABLE",
  MOVEABLE = "MOVEABLE",
  LONG_WEEKEND = "LONG_WEEKEND",
}
