export enum PermissionsEnum {
  DASHBOARD = "DASHBOARD",
  CONSULTATION = "CONSULTATION",
  APPOINTMENT_MANAGEMENT = "APPOINTMENT_MANAGEMENT",
  SUPPLIES = "SUPPLIES",
  FINANCE = "FINANCE",
  REPORTS = "REPORTS",
  CONFIGURATION = "CONFIGURATION",
  SYSTEM = "SYSTEM",
  PATIENTS = "PATIENTS",
}

export enum ActionsEnum {
  READ = "READ",
  CREATE = "CREATE",
  DELETE = "DELETE",
  UPDATE = "UPDATE",
  UPLOAD = "UPLOAD",
}
