export enum LockTypeModeEnum {
  POINTUAL = "POINTUAL",
  DAYS_IN_RANGE_NO_RECURRENCE = "DAYS_IN_RANGE_NO_RECURRENCE",
  DAILY_CONTINUOUS = "DAILY_CONTINUOUS",
  RECURRENT_PATTERN = "RECURRENT_PATTERN",
}
