import { NgModule } from "@angular/core";

import { TablerIconsModule } from "angular-tabler-icons";
import {
  IconBrandGoogle,
  IconAlertTriangle,
  IconAlertCircle,
  IconCircleCheck,
  IconXboxX,
  IconSettings,
  IconFileDollar,
  IconSun,
  IconMoon,
  IconSearch,
  IconChevronDown,
  IconUserCircle,
  IconLogout2,
  IconDeviceDesktopCog,
  IconPackages,
  IconMenu,
  IconChartBar,
  IconEdit,
  IconCalendarPlus,
  IconFolderPlus,
  IconFolderSearch,
  IconChartHistogram,
  IconPlus,
  IconArrowNarrowLeft,
  IconUserSquareRounded,
  IconRectangle,
  IconRectangleRoundedBottom,
  IconRectangleRoundedTop,
  IconRectangleVertical,
  IconSquare,
  IconExclamationCircle,
  IconEqual,
  IconBuildingBridge2,
  IconCircleFilled,
  IconRectangleFilled,
  IconCodeVariable,
  IconLetterTSmall,
  IconLetterCSmall,
  IconLetterASmall,
  IconSlash,
  IconLetterXSmall,
  IconLetterPSmall,
  IconLetterDSmall,
  IconLetterOSmall,
  IconLetterISmall,
  IconLetterMSmall,
  IconLetterSSmall,
} from "angular-tabler-icons/icons";

const ICONS = {
  IconBrandGoogle,
  IconAlertTriangle,
  IconAlertCircle,
  IconCircleCheck,
  IconXboxX,
  IconSettings,
  IconFileDollar,
  IconSun,
  IconMoon,
  IconSearch,
  IconChevronDown,
  IconUserCircle,
  IconLogout2,
  IconDeviceDesktopCog,
  IconPackages,
  IconMenu,
  IconChartBar,
  IconEdit,
  IconCalendarPlus,
  IconFolderPlus,
  IconFolderSearch,
  IconChartHistogram,
  IconPlus,
  IconArrowNarrowLeft,
  IconUserSquareRounded,
  IconSquare,
  IconRectangleRoundedBottom,
  IconRectangleRoundedTop,
  IconExclamationCircle,
  IconEqual,
  IconBuildingBridge2,
  IconCircleFilled,
  IconRectangleFilled,
  IconCodeVariable,
  IconLetterTSmall,
  IconLetterCSmall,
  IconLetterASmall,
  IconSlash,
  IconLetterXSmall,
  IconLetterPSmall,
  IconLetterDSmall,
  IconLetterOSmall,
  IconLetterISmall,
  IconLetterMSmall,
  IconLetterSSmall,
} as const;

@NgModule({
  imports: [TablerIconsModule.pick(ICONS)],
  exports: [TablerIconsModule],
})
export class IconsModule {}
