#Configuraciones varias
spring.application.name=odontologiaintegralfm-api
app.version=1.0.0
app.env=dev


info.app.name=${spring.application.name}
info.app.version=${app.version}
info.app.env=${app.env}





#Configuraci\u00F3n swagger
springdoc.swagger-ui.doc-expansion=none


#Configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}

#Consulta por consola
#spring.jpa.show-sql=true

#Formatea el SQL para que sea legible.
#spring.jpa.properties.hibernate.format_sql=true

#Activa el log real de Hibernate, no el b\u00E1sico.
#logging.level.org.hibernate.SQL=DEBUG

#Muestra los valores reales que se bindearon al SQL
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#Configuraci\u00F3n de mensajes
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600
spring.messages.always-use-message-format=true
spring.web.locale=es_AR
spring.web.locale-resolver=fixed


# Configuraci\u00F3n del nivel de logs (por ejemplo, ERROR, WARN, INFO)
#logging.level.org.springframework.web=ERROR
#logging.level.com.tu.paquete=ERROR

# Establecer la ubicaci\u00F3n del archivo de logs.
#logging.file.name=logs/app.log

# Configuraci\u00F3n de logback
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


#Config de JWT
security.jwt.private.key=${PRIVATE_KEY}

#Usuario generador del Token
security.jwt.user.generator=${USER_GENERATOR}

#Configuraci\u00F3n para Google -- oauth2 --
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


# Configuraciones b\u00E1sicas del servidor de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

# Propiedades adicionales para autenticaci\u00F3n y cifrado
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true

# Configuraci\u00F3n de tama\u00F1o m\u00E1ximo de archivos aceptado por Spring.
spring.servlet.multipart.max-file-size=-1MB
spring.servlet.multipart.max-request-size=-1MB

# Configuraci\u00F3n de Im\u00E1genes
file.upload-dir.image=c:/uploads/avatars
# Configuraci\u00F3n de Documentos
file.upload-dir.document=c:/uploads/documents


#Paginaci\u00F3n de getAll
pagination.default-page= 0
pagination.default-size= 10
pagination.default-direction=asc

pagination.default-sortBy= id
pagination.default.user-sortBy= username
pagination.default.patient-sortBy= person.lastName
pagination.default.calendarHoliday-sortBy= date

#TempalteEmail
email.template.path=templates/email-template.html
email.logo.path=static/logo-fm.png
email.logo.cid=logoImagen


#WebSocket
websocket.endpoint=/ws
websocket.app-prefix=/app
websocket.broker-prefix=/topic
websocket.allowed-origins=${ALLOWED_ORIGINS}
websocket.use-sockjs=false

